[2024-06-13T05:46:48.299+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_to_s3_to_redshift.delete_s3_file manual__2024-06-13T05:46:15.022393+00:00 [queued]>
[2024-06-13T05:46:48.320+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_to_s3_to_redshift.delete_s3_file manual__2024-06-13T05:46:15.022393+00:00 [queued]>
[2024-06-13T05:46:48.321+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-06-13T05:46:48.357+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): delete_s3_file> on 2024-06-13 05:46:15.022393+00:00
[2024-06-13T05:46:48.372+0000] {standard_task_runner.py:57} INFO - Started process 245 to run task
[2024-06-13T05:46:48.380+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'api_to_s3_to_redshift', 'delete_s3_file', 'manual__2024-06-13T05:46:15.022393+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/test_redshift_real.py', '--cfg-path', '/tmp/tmpgzg2dv1k']
[2024-06-13T05:46:48.381+0000] {standard_task_runner.py:85} INFO - Job 121: Subtask delete_s3_file
[2024-06-13T05:46:48.477+0000] {task_command.py:410} INFO - Running <TaskInstance: api_to_s3_to_redshift.delete_s3_file manual__2024-06-13T05:46:15.022393+00:00 [running]> on host 6be9063e1a69
[2024-06-13T05:46:48.672+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='api_to_s3_to_redshift' AIRFLOW_CTX_TASK_ID='delete_s3_file' AIRFLOW_CTX_EXECUTION_DATE='2024-06-13T05:46:15.022393+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-13T05:46:15.022393+00:00'
[2024-06-13T05:46:48.703+0000] {base.py:73} INFO - Using connection ID 'aws_s3' for task execution.
[2024-06-13T05:46:48.704+0000] {connection_wrapper.py:337} INFO - AWS Connection (conn_id='aws_s3', conn_type='aws') credentials retrieved from login and password.
[2024-06-13T05:46:50.153+0000] {s3.py:951} INFO - Deleted: ['dataSource/api_raw_data.csv']
[2024-06-13T05:46:50.155+0000] {python.py:183} INFO - Done. Returned value was: None
[2024-06-13T05:46:50.170+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=api_to_s3_to_redshift, task_id=delete_s3_file, execution_date=20240613T054615, start_date=20240613T054648, end_date=20240613T054650
[2024-06-13T05:46:50.239+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-06-13T05:46:50.268+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
